### ISSUE TITLE
Please add JTV support

### ISSUE THREAD

**Issue by HDaemon666** [Cigaras/IPTV.bundle#10]
It will be useful thing if users can see TV program guide for the current channel.  JTV Example http://www.teleguide.info/download/new3/jtv.zip.

**Comment by Cigaras** [comment]
I agree, it would be nice for users to see TV program guide, this feature has the highest priority in my [To do list](https://github.com/Cigaras/IPTV.bundle/blob/master/README.md#to-do-list), but because of [poor Plex support](https://github.com/Cigaras/IPTV.bundle/blob/master/README.md#compatible-devices-and-limitations) regarding live streams I doubt I will keep on working on this plug-in or using Plex at all. [XBMC (Kodi)](http://kodi.wiki/view/Add-on:IPTV_Simple_Client) and [Media Portal](http://wiki.team-mediaportal.com/1_MEDIAPORTAL_1/141_Configuration/TV-Server_Configuration/02_TV_Servers/0_IPTV_(DVB-IP)) work much better with live TV than Plex.

**Comment by HDaemon666** [comment]
Thnx for reply. I understand your position about Plex, but still pending, with a little hope. :)

**Comment by Cigaras** [comment]
[EPG](https://github.com/Cigaras/IPTV.bundle/wiki/Program-guide) is available in [latest versions](https://github.com/Cigaras/IPTV.bundle/releases).
