### ISSUE TITLE
Reload the .m3u file automatically every time you connect

### ISSUE THREAD

**Issue by YoannZ** [Cigaras/IPTV.bundle#116]
Hello I would like to be able to reload the .m3u file automatically with each connection.
I should edit code but I tested a lot in m3u_parser.py but nothing works.

help me please

**Comment by Cigaras** [comment]
I have this planned in next update, just am a bit short on time, should be done this or next week.

**Comment by Cigaras** [comment]
Playlist is reloaded automatically every time starting the plug-in if option in preferences "[At what hour should plug-in automatically reload the M3U files?](https://github.com/Cigaras/IPTV.bundle/wiki/Preferences)" is set to "never", however please keep in mind that Plex likes to keep plug-ins in the background so it might require to restart the Plex Media Server for playlist to reload. You can always force playlist reload manually by enabling manual reload in [preferences](https://github.com/Cigaras/IPTV.bundle/wiki/Preferences) (11th option) and clicking new button in the main menu:
<img src="https://us.v-cdn.net/6025034/uploads/editor/d3/p0iee8rmabbn.png" width="49%"/> <img src="https://us.v-cdn.net/6025034/uploads/editor/p7/bczrfrz9lape.png" width="49%"/>

**Comment by YoannZ** [comment]
In the previous updates, the .m3u file is updated automatically.
I do not understand why on the new update it is impossible to find out why.
What do you think this line of code is?

**Comment by Cigaras** [comment]
I can not reproduce the problem You are having. Maybe You are misunderstanding the concept: in version 1.x playlist was reloaded every time entering the menu (like now in [IPTVLite](https://github.com/Cigaras/IPTVLite.bundle)) but it was inconvenient to browse the channels with bigger playlists because after every click user had to wait for plug-in to read whole playlist again and again. Because of that in version 2.x playlist is cached and reloads only on set time once per day or when plug-in is started (for most users this is enough, they just set the playlist and use it without constant edits). However plug-in start is not always registered by Plex Server so it might require to restart the server. If you need to constantly edit the playlist, just use manual reload button.

If You're dying to cripple Your usage experience, change [line 95 in init.pty](https://github.com/Cigaras/IPTV.bundle/blob/master/Contents/Code/__init__.py#L95) file from
```    if not Dict['groups']:```
to
```    if True:```
and leave automatic update on "never".
