### ISSUE TITLE
[Transcoding] Playback Error with Transcoding

### ISSUE THREAD

**Issue by TheDaChicken** [Cigaras/IPTV.bundle#142]
Hello, I just got your plugin and I was testing it out and I can't even play anything I get this Error:
![playback error](https://user-images.githubusercontent.com/19061444/29086855-ca9cc82e-7c28-11e7-917a-a023d18b8a14.PNG)

Can you fix it?

Plex Server: Version 1.7.5.4035 
Client: Web
What Version: GetHub - Code Download

**Comment by GoNotCougsWA** [comment]
I found out you have to disable Direct Stream and Direct Play But it would be nice if you fixed that so I don't have too

**Comment by Cigaras** [comment]
I can not fix that because plug-in does not play media by itself, it is played by Plex client and most clients have limited playback capabilities so direct playback is not possible and transcoding is required.

More information can be found in plug-ins wiki pages [Compatibility and limitations](https://github.com/Cigaras/IPTV.bundle/wiki/Compatibility-and-limitations) and [Troubleshooting](https://github.com/Cigaras/IPTV.bundle/wiki/Troubleshooting).

**Comment by GoNotCougsWA** [comment]
Just a little UPDATE:

Plex has now supporting DASH and http streams.

For right now, You can use only Plex Media Player to play them and run 24/7.
Now I don't know if this is a Plex Pass beta update but the update was on Plex Media Server: 1.9.7.4441.


I am going to check if your plugin is running 24/7.

I have checked on CcloudTv Channel Plugin.
