### ISSUE TITLE
Cant select particular channel in plex HT for linux

### ISSUE THREAD

**Issue by Yurko-Fedoriv** [Cigaras/IPTV.bundle#15]
Here is an issue: I can't select particular channel from the list of channels in plex HT for linux (ubuntu in my case, 1.3.6.441-201502051421-ubuntu79~ubuntu14.04.1).
When selected (enter on keyboard or select in any remote app) nothing happens. 
Works fine withing android application, also I can use play button on the left side and switch through the channels with arrows.

Any chance you may have an idea how to fix this?

**Comment by Cigaras** [comment]
Plex HT does not play any live streams at all, or at least I am unable to make it play them, nothing works...

**Comment by Yurko-Fedoriv** [comment]
Mine does work. But for the mentioned issue.
This one launches the first channel
![image](https://cloud.githubusercontent.com/assets/1327761/6958921/1e8463e2-d91b-11e4-9e80-3cb814adf2c1.png)

But I can't launch channel from the list
![image](https://cloud.githubusercontent.com/assets/1327761/6958926/4107828c-d91b-11e4-9be2-901402112f7b.png)

**Comment by Cigaras** [comment]
I have Plex HT version 1.3.5.431, dtrams do not play, and my channels menu looks like this, everything works except for playback, so I am not sure how to help You because I can not reproduce the problem
![screenshot 2015-04-02 13 25 25](https://cloud.githubusercontent.com/assets/244432/6962306/0c139a5e-d93c-11e4-9305-57620f0a031a.png)
Maybe later if I have time I'll run a Ubuntu VM, buts it's Easter and I have quite a busy week...

**Comment by mike-pt** [comment]
For me no channel is selectable, I can see the channel list as shown in the screen above but when pressing enter in any channel nothing happens.

**Comment by Cigaras** [comment]
Using latest Plex Home Theater software (version 1.4.1.469-47a90f01) for Windows my playlist works without issues, I might say something more if I got a playlist to reproduce the problem.

**Comment by Cigaras** [comment]
Looks like same issue occurred for other players like Rasplex #76, and now everything works in version [2.0.0](https://github.com/Cigaras/IPTV.bundle/releases)
