### ISSUE TITLE
Custom user agent 

### ISSUE THREAD

**Issue by daveftw84** [Cigaras/IPTV.bundle#156]
It's not working for me using the latest version I added the useragent and after a sniff I noticed it's not applying it

**Comment by Cigaras** [comment]
I have no way to test it because I do not watch streams that require custom user agent, it did work #79 and nothing was changed since then.

**Comment by daveftw84** [comment]
I put the custom useragent in to the string. Every stream I play fails when
I did a packet sniff while playing a stream I noticed the useragent was far
from what I changed it to

**Comment by daveftw84** [comment]
Let me know if you need it m3u the test with now I will gladly give you one

**Comment by Cigaras** [comment]
Yes, I need a sample stream, but I am quite busy and am not sure when I'll be able to check it.

Also I need You to teach me how to check that user agent.

**Comment by daveftw84** [comment]
It's quite simple all you need is a packet capture application installed on
the target device and capture the request being sent

**Comment by daveftw84** [comment]
I packaged sniff Plex trying to play a stream

**Comment by Cigaras** [comment]
I still have no sample stream and no idea how to check if custom user agent works or not.

According to [documentation](https://us.v-cdn.net/6025034/uploads/editor/rg/jxvpxxxt63r6.pdf) page 70 this is the way to set a custom user agent:
```
HTTP.Headers[’User-Agent’] = ’My Plug-in’
```
So my plug-in sets this every time Play button is clicked (lines [274-276](https://github.com/Cigaras/IPTV.bundle/blob/master/Contents/Code/__init__.py#L274-L276) in `__init__.py` file):
```
    # Custom User-Agent string
    if Prefs['user_agent']:
        HTTP.Headers['User-Agent'] = Prefs['user_agent']
```
If You want You can remove this `if` statement and replace it with a hard-coded declaration like mentioned above, but I doubt it will have any effect, and there is nothing else I can suggest...

**Comment by daveftw84** [comment]
send me an email at daveftw84@gmail.com
and ill send you a m3u and the correct user agent.
anyway i can send requestss thro a proxy to hide/forge the useragent?

**Comment by daveftw84** [comment]
m scared to post it on here. its a paid service

**Comment by Lunaden** [comment]
Hi, any news from this ?

**Comment by Lunaden** [comment]
Work when adding 
```
ObjectContainer.user_agent = 'my-agent'
```
to ___init.py___ in def Start():

**Comment by daveftw84** [comment]
[image: Inline image 1]

**Comment by daveftw84** [comment]
i got it, sweet. thanks

**Comment by Cigaras** [comment]
Just [committed](https://github.com/Cigaras/IPTV.bundle/commit/79e890c50775c9ec60dd39943c16113254823bf7) a new version that uses both methods to set the user agent string – the `HTTP.Headers[’User-Agent’]` and `ObjectContainer.user_agent`. To get this version click Clone or download -> [Download ZIP](https://github.com/Cigaras/IPTV.bundle/archive/master.zip) on [the front page of this repository](https://github.com/Cigaras/IPTV.bundle).

In addition to that it is now possible to specify user agent string for every stream individually using M3U attribute [`user_agent`](https://github.com/Cigaras/IPTV.bundle/wiki/Playlist#advanced-attributes) or directive [`#EXTVLCOPT:http-user-agent`](https://github.com/Cigaras/IPTV.bundle/issues/164).

However I do not have a way to test it properly, that's why I did not make a release version of it jet, please test it and report Your findings.

**Comment by daveftw84** [comment]
it works

**Comment by HarryElSuzio** [comment]
please add new line in  your code  per http-referrer i need add user agent and referrer per ini channel  its posibol?

**Comment by Cigaras** [comment]
Referer added in version [2.1.9](https://github.com/Cigaras/IPTV.bundle/releases/tag/v2.1.9)
