### ISSUE TITLE
Playlist symlink doesn't work

### ISSUE THREAD

**Issue by kampiamodikuesto** [Cigaras/IPTV.bundle#160]
hi, i try to use a symlink as playlist pointing to the destination file on my cloud folder but i get an error.
isn't possibile to use symlink?

**Comment by Cigaras** [comment]
I doubt that.

If your playlist path starts with `http` plug-in will try to load it using `[HTTP.Requests](https://github.com/Cigaras/IPTV.bundle/blob/master/Contents/Code/m3u_parser.py#L52)` method ([documentation page 69](https://us.v-cdn.net/6025034/uploads/editor/rg/jxvpxxxt63r6.pdf)), otherwise plug-in assumes that file is local and will try to load it using `[Resource.Load](https://github.com/Cigaras/IPTV.bundle/blob/master/Contents/Code/m3u_parser.py#L56)` method ([documentation page 66](https://us.v-cdn.net/6025034/uploads/editor/rg/jxvpxxxt63r6.pdf)). Both methods are internal Plex methods so if Plex is able to use symlinks then plug-in should too, and if not then not 😄
