### ISSUE TITLE
IPTV Error

### ISSUE THREAD

**Issue by jrhopkins1** [Cigaras/IPTV.bundle#217]
Plug In will load all channels but will not play via any app. It will work fine with a web browser only. Error: Playback was not possible. Not enough CPU for conversion of this item. Any ideas?

**Comment by jrhopkins1** [comment]
Update - It seems the Xbox One Plex app will still load the streams. Android/Fire TV will not.

**Comment by Cigaras** [comment]
First is a Plex issue, check [Plex forums](https://forums.plex.tv/t/not-enough-cpu-for-conversion-of-this-item-after-plex-update/189195/7), might be already fixed in latest Plex server version.

Second looks like same issue as #231 and others, [Plex is killing plug-ins altogether](https://www.plex.tv/blog/subtitles-and-sunsets-big-improvements-little-housekeeping/).
