### ISSUE TITLE
Adding playlist from TVHEADEND - Error loading player: No playable sources found

### ISSUE THREAD

**Issue by krzpal** [Cigaras/IPTV.bundle#26]
After adding playlist from tvheadend I got error:

#EXTM3U
#EXTINF:-1,Boomerang
http://192.168.1.220:9981/stream/channelid/510093570?ticket=39BC31958AD213243D395040CF92955C0DDF28D2&profile=pass
#EXTINF:-1,VOD 203
http://192.168.1.220:9981/stream/channelid/1813204932?ticket=9CC8E606E97526D81426B4E5D2AA54D5F9466AFB&profile=pass

Same time all is working using VLC, but I need to add it for ROKU Plex player.

Plex Server on Windows 10 - version 0.9.12.19 

Error loading player:
No playable sources found

How to fix this ?

**Comment by Cigaras** [comment]
Try the [TVHeadend channel](https://forums.plex.tv/discussion/151413/tvplexendchannel-bundle-a-tvheadend-channel-plugin-for-plex-media-server), but it is likely You will get the same result because it is ROKU Plex players issue as [it is unable to play/decode/transcode the stream](https://github.com/Cigaras/IPTV.bundle#compatible-devices-and-limitations).
