### ISSUE TITLE
Remove preference window

### ISSUE THREAD

**Issue by freddysmith1** [Cigaras/IPTV.bundle#65]
Hi, is there anyway i can remove the preference window from the plug-in once its all setup so no one can change anything ?

**Comment by Cigaras** [comment]
[Added](https://github.com/Cigaras/IPTV.bundle/commit/788babf7617aef7b2f3e9d80033097c1f4249713) an option to preferences to show preferences in players, by default it's unchecked because I noticed that many clients are unable to show these preferences anyway. It is not possible to hide 'em from server configuration however.

If You do not want to bother with [GitHub zip](https://github.com/Cigaras/IPTV.bundle/archive/master.zip) this will be available in release [1.2.9](https://github.com/Cigaras/IPTV.bundle/releases) shortly.

**Comment by freddysmith1** [comment]
Cheers mate . absolute star
